apiVersion: v1
kind: List
items:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: 'jaeger'
    spec:
      selector:
        app: 'jaeger'
      serviceName: 'jaeger'
      replicas: 1
      template:
        metadata:
          labels:
            app: 'jaeger'
        spec:
          containers:
            - image: 'quay.io/jaegertracing/all-in-one:1.21.0'
              name: 'jaeger'
              ports:
                - containerPort: 5775
                  protocol: UDP
                - containerPort: 6831
                  protocol: UDP
                - containerPort: 6832
                  protocol: UDP
                - containerPort: 5778
                  protocol: TCP
                - containerPort: 14268
                  protocol: TCP
                - containerPort: 16686
                  protocol: TCP
                - containerPort: 9411
                  protocol: TCP
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: 'jaeger-api'
      labels:
        app: 'jaeger'
    spec:
      ports:
        - name: jaeger-api
          port: 14268
          protocol: TCP
          targetPort: 14268
      selector:
        app: 'jaeger'
  - apiVersion: v1
    kind: Service
    metadata:
      name: 'jaeger-ui'
      labels:
        app: 'jaeger'
    spec:
      ports:
        - name: jaeger-ui
          port: 16686
          protocol: TCP
          targetPort: 16686
      selector:
        app: 'jaeger'
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: jaeger-ui
    spec:
      to:
        name: jaeger-ui
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: jaeger-api
    spec:
      to:
        name: jaeger-api