---
apiVersion: "v1"
kind: "List"
items:
  - apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "${SERVICE_NAME}"
      labels:
        app.kubernetes.io/runtime: "quarkus"
        app.kubernetes.io/name: "${SERVICE_NAME}"
    spec:
      type: NodePort
      ports:
        - name: "http"
          port: ${INTERNAL_PORT}
          targetPort: 8080
          protocol: TCP
      selector:
        app.kubernetes.io/name: "${SERVICE_NAME}"

  - apiVersion: "apps/v1"
    kind: "Deployment"
    metadata:
      labels:
        app.kubernetes.io/runtime: "quarkus"
        app.kubernetes.io/name: "${SERVICE_NAME}"
      name: "${SERVICE_NAME}"
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: "${SERVICE_NAME}"
      template:
        metadata:
          labels:
            app.kubernetes.io/runtime: "quarkus"
            app.kubernetes.io/name: "${SERVICE_NAME}"
            deployment: "${SERVICE_NAME}"
        spec:
          containers:
            - image: "${IMAGE}"
              name: "${SERVICE_NAME}"
              ports:
                - containerPort: ${INTERNAL_PORT}
                  name: "http"
                  protocol: "TCP"
