apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: registry
      labels:
        app: registry
    spec:
      ports:
        - port: ${KAFKA_REGISTRY_PORT}
          targetPort: ${KAFKA_REGISTRY_PORT}
          name: client
      selector:
        app: registry
  - apiVersion: "apps/v1"
    kind: "Deployment"
    metadata:
      name: registry
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: registry
      template:
        metadata:
          labels:
            app: registry
        spec:
          containers:
            - name: kafka-registry
              image: ${KAFKA_REGISTRY_IMAGE}
              env:
                - name: QUARKUS_PROFILE
                  value: "prod"
                - name: APPLICATION_ID
                  value: "registry_id"
                - name: KAFKA_BOOTSTRAP_SERVERS
                  value: "${KAFKA_BOOTSTRAP_URL}"
                - name: APPLICATION_SERVER
                  value: "localhost:9000"
              ports:
                - containerPort: ${KAFKA_REGISTRY_PORT}
                  name: client
          restartPolicy: Always
      triggers:
      - type: "ConfigChange"
kind: List
metadata: {}