name-template: '1.0.z 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
exclude-labels:
  - 'skip-changelog'
  - 'release'
categories:
  - title: '🚀 New features and improvements'
    labels:
      - 'new'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- #$NUMBER: $TITLE (@$AUTHOR)'
template: |
  ## Changes
  $CHANGES
  All contributors: $CONTRIBUTORS