name: 'Release Quarkus QE Test Framework'
description: 'Releases Quarkus QE Test Framework'
inputs:
  repository-id:
    description: 'Must match a repository id present in of the POM file distributionManagement repositories'
    required: true
  release-version:
    description: 'Version under which should this framework be released'
runs:
  using: "composite"
  steps:
    - name: Install JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        check-latest: true
        server-id: ${{ inputs.repository-id }}
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Set Quarkus QE Test Framework version to ${{ inputs.release-version }}
      shell: bash
      run: mvn -B versions:set -DnewVersion=$NEW_FRAMEWORK_VERSION
      env:
        NEW_FRAMEWORK_VERSION: ${{ inputs.release-version }}
    - name: Maven release ${{ inputs.release-version }}
      shell: bash
      run: |
        mvn -B -DskipTests -DskipITs \
          -DretryFailedDeploymentCount=3 \
          -Prelease,framework \
          clean deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Delete Local Artifacts From Cache
      shell: bash
      run: rm -r ~/.m2/repository/io/quarkus/qe

