package io.quarkus.test.services;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import io.quarkus.test.bootstrap.ManagedResourceBuilder;
import io.quarkus.test.services.quarkus.ProdQuarkusApplicationManagedResourceBuilder;

@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface QuarkusApplication {
    // By default, it will load all the classes in the classpath.
    Class<?>[] classes() default {};

    /**
     * If this is set to true, all classes from application's main/src will always be included.
     * Otherwise, if QuarkusApplication.classes() is set, only classes explicitly stated in classes() will be loaded.
     * This option is meant for cases, when you have a lot of classes in main/src and want to add some more,
     * from other place (like from test/src).
     * In that case, you need only to set this flag to true, and list desired additional classes in classes().
     */
    boolean includeAllClassesFromMain() default false;

    Class<? extends ManagedResourceBuilder> builder() default ProdQuarkusApplicationManagedResourceBuilder.class;

    /**
     * @return the properties file to use to configure the Quarkus application.
     */
    String properties() default "application.properties";

    /**
     * Add forced dependencies.
     */
    Dependency[] dependencies() default {};

    /**
     * Use additional BOMs for import.
     */
    Dependency[] boms() default {};

    /**
     * Enable SSL configuration. This property needs `quarkus.http.ssl.certificate.key-store-file` and
     * `quarkus.http.ssl.certificate.key-store-password` to be set.
     */
    boolean ssl() default false;

    /**
     * Certificates that should be generated by this framework.
     */
    Certificate[] certificates() default {};

    /**
     * Enable GRPC configuration. This property will map the gPRC service to a random port.
     */
    boolean grpc() default false;

    /**
     * This option only works with ssl() == true.
     * Create TLS pass-through route on OpenShift to this specific port on app.
     */
    int ocpTlsPort() default 8443;
}
