apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: '${SERVICE_NAME}'
    spec:
      selector:
        matchLabels:
          app: '${SERVICE_NAME}'
      serviceName: '${SERVICE_NAME}'
      replicas: 1
      template:
        metadata:
          labels:
            app: '${SERVICE_NAME}'
        spec:
          volumes:
            - name: tempo-data
              emptyDir: { }
            - name: loki-data
              emptyDir: { }
            - name: grafana-data
              emptyDir: { }
            - name: loki-storage
              emptyDir: { }
            - name: p8s-storage
              emptyDir: { }
            - name: pyroscope-storage
              emptyDir: { }
            - name: "tempo-var"
              emptyDir: { }
          containers:
            - image: '${IMAGE}'
              name: '${SERVICE_NAME}'
              # NOTE: By default OpenShift does not allow writing the root directory.
              # See: https://github.com/grafana/docker-otel-lgtm/issues/132
              volumeMounts:
                - name: tempo-data
                  mountPath: /data/tempo
                - name: grafana-data
                  mountPath: /data/grafana
                - name: loki-data
                  mountPath: /data/loki
                - name: loki-storage
                  mountPath: /loki
                - name: p8s-storage
                  mountPath: /data/prometheus
                - name: pyroscope-storage
                  mountPath: /data/pyroscope
                # 0.29.0 using tempo 3, and it seems to have problem with permission same as above
                - name: "tempo-var"
                  mountPath: "/var/tempo"
              ports:
                - containerPort: ${WEB_UI_PORT}
                  protocol: TCP
                - containerPort: ${LOKI_API_PORT}
                  protocol: TCP
                - containerPort: ${TEMPO_API_PORT}
                  protocol: TCP
                - containerPort: ${PROMETHEUS_API_PORT}
                  protocol: TCP
                - containerPort: ${OTLP_GRPC_PORT}
                  protocol: TCP
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: '${SERVICE_NAME}-web'
      labels:
        app: '${SERVICE_NAME}'
    spec:
      ports:
        - name: '${SERVICE_NAME}-web'
          port: ${WEB_UI_PORT}
          protocol: TCP
          targetPort: ${WEB_UI_PORT}
      selector:
        app: '${SERVICE_NAME}'
  - apiVersion: v1
    kind: Service
    metadata:
      name: '${SERVICE_NAME}-loki'
      labels:
        app: '${SERVICE_NAME}'
    spec:
      ports:
        - name: '${SERVICE_NAME}-loki'
          port: ${LOKI_API_PORT}
          protocol: TCP
          targetPort: ${LOKI_API_PORT}
        - name: '${SERVICE_NAME}-tempo'
          port: ${TEMPO_API_PORT}
          protocol: TCP
          targetPort: ${TEMPO_API_PORT}
        - name: '${SERVICE_NAME}-prometheus'
          port: ${PROMETHEUS_API_PORT}
          protocol: TCP
          targetPort: ${PROMETHEUS_API_PORT}
      selector:
        app: '${SERVICE_NAME}'
  - apiVersion: v1
    kind: Service
    metadata:
      name: '${SERVICE_NAME}-tempo'
      labels:
        app: '${SERVICE_NAME}'
    spec:
      ports:
        - name: '${SERVICE_NAME}-tempo'
          port: ${TEMPO_API_PORT}
          protocol: TCP
          targetPort: ${TEMPO_API_PORT}
      selector:
        app: '${SERVICE_NAME}'
  - apiVersion: v1
    kind: Service
    metadata:
      name: '${SERVICE_NAME}-prometheus'
      labels:
        app: '${SERVICE_NAME}'
    spec:
      ports:
        - name: '${SERVICE_NAME}-prometheus'
          port: ${PROMETHEUS_API_PORT}
          protocol: TCP
          targetPort: ${PROMETHEUS_API_PORT}
      selector:
        app: '${SERVICE_NAME}'
  - apiVersion: v1
    kind: Service
    metadata:
      name: '${SERVICE_NAME}-collector'
      labels:
        app: '${SERVICE_NAME}'
    spec:
      ports:
        - name: '${SERVICE_NAME}-collector'
          port: ${OTLP_GRPC_PORT}
          protocol: TCP
          targetPort: ${OTLP_GRPC_PORT}
      selector:
        app: '${SERVICE_NAME}'
